<link href="/css/bootstrap.iso.css" rel="stylesheet" >
	<link rel="stylesheet" type="text/css" href="/css/bootstrap-datetimepicker.min.css">

<h1>Orden</h1><br>
<div class="row">
	<div class="col-lg-12">
		<form action="/orden/requestordenadd" method="POST" enctype="multipart/form-data">
			<div class="row text-left">
				<div class="col-lg-12">
					<label for="text"><h4>Nombre de Orden: </h4></label>
					<p><input type="text" name="name" class="form-control" placeholder="Ingrese un nombre descriptivo para su orden"></p>
				</div>				
			</div>
			
			<div class="row text-left">
				<div class="col-lg-12">
					<label for="text"><h4>Direccion: </h4></label>
				<p><select name="iddireccion" class="form-control" required>
					<option value="">Escoge una de tus Direcciones disponibles:</option>
					<?php foreach ($this->direccion as $key) { ?>
						<option value="<?php echo $key["id"]; ?>" ><?php echo $key["direccion"]; ?></option>
					<?php } ?>
				</select></p>
				</div>	
			</div>
			<div class="row text-left">
				<div class="col-lg-12">
					<label for="text"><h4>Nombre de quien Recibe: </h4></label>
					<p><input type="text" name="recibe" class="form-control" placeholder="Nombre del destinatario"></p>
				</div>
			</div>
			<div class="row text-left">
				<div class="col-lg-12">
					<label><h4>Fecha de entrega: </h4></label>
					<div class="bootstrap">	
						<input  type="text" name="fecha" id="datepicker" class="form-control" ><br />
					</div>
					<label><h4>Hora de entrega: </h4></label>
					<div class="bootstrap">	
						<input  type="text" name="hora" id="hourpicker" class="form-control" ><br />
					</div>
				</div>	
			</div>
				<input type="hidden" name="complete" value="0">
				<input type="hidden" name="rejected" value="0">
				<input type="hidden" name="active" value="0">
			<div class="col-lg-12 text-center"><br>
				<p><input type="submit" value="Crear Orden" class="btn btn-primary"></p>
			</div><br>
		</form>
	</div>	
</div>

<script type="text/javascript">

	$(document).ready(function(){
		$('#datepicker').datetimepicker({ format: 'YYYY-MM-DD'});
		$('#hourpicker').datetimepicker({ format: 'LTS'});
		});

</script>
