<div class="row">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-5">
		    	<h3>Datos de Entrega</h3>
		    	<table class="table table-bordered table-striped">                    
			        <thead>
			            <tr>
			                <th>Fecha de Entrega</th>
			                <th>Hora de Entrega</th>
			                <th>Direccion</th>
			                <th>Quien Recibe</th>
			            </tr>
			        </thead>
			        <tbody>
			            <?php foreach ($this->pedidosdire as $key){ ?>
			                    <tr>

			                        <td><p><?php echo $key["fechadeentrega"]; ?></p></td>
			                        <td><p><?php echo $key["horadeentrega"]; ?></p></td>
			                        <td><p><?php echo $key["direccion"];?></p></td>
			                        <td><p><?php echo $key["nombrerecibe"];?></p></td>
			                    </tr>    
			            <?php  } ?>
			        </tbody>  
			    </table>
			    <h3>Datos Cliente</h3>
		    	<table class="table table-bordered table-striped">                    
			        <thead>
			            <tr>
			                <th>Nobre</th>
			                <th>Apellido Paterno</th>
			                <th>Apellido Materno</th>
			                <th>Direccion</th>
			                <th>Telefono</th>
			                <th>Correo</th>
			            </tr>
			        </thead>
			        <tbody>
			            <?php 
			                foreach ($this->usuario as $key){ ?>
			                    <tr>
			                        <td><p><?php echo $key["nombre"]; ?></p></td>
			                        <td><p><?php echo $key["ap"];?></p></td>
			                        <td><p><?php echo $key["am"];?></p></td>
			                        <td><p><?php echo $key["direccion"];?></p></td>
			                        <td><p><?php echo $key["telefono"];?></p></td>
			                        <td><p><?php echo $key["correo"];?></p></td>
			                    </tr>    
			            <?php  } ?>
			        </tbody>  
			    </table>
		    </div>
			<div class="col-md-7">
				<h3>Productos</h3>
			    <table class="table table-bordered table-striped">                    
			        <thead>
			            <tr>
			                <th>Id</th>
			                <th>nombre producto</th>
			                <th>cantidad</th>
			                <th>Precio</th>
			            </tr>
			        </thead>
			        <tbody>
			            <?php $cont =1;
			                foreach ($this->pedidos as $key){ ?>
			                    <tr>
			                        <th scope="row"><?php echo $cont++; ?></th>
			                        <td><p><?php echo $key["nombre"]; ?></p></td>
			                        <td><p><?php echo $key["cantidad"];?></p></td>
			                        <td><p><?php echo $key["precio"];?></p></td>
			                    </tr>    
			            <?php  } ?>
			        </tbody>  
			    </table>
		    </div>
		    
	    </div>
	</div> 
</div>