<div class="col-md-12">
	<div class="white-box">
		<div class="jumbotron" style="background-image: url('/img/flowers.jpg'); background-size: cover;
		background-position: top center; ">
			<h1>Gestion de flores</h1>	
		</div>
		<?php $session = new Zend_Session_Namespace("current_session"); 
        		echo $session->nombre;
			?>
	</div>
</div>
<div class="col-md-12">
	<div class="white-box">
		<form action="/panel/requestaddflowers" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="form-group">
				<label for="text">Nombre:</label>
				<input type="text" name="name" class="form-control" placeholder="Ingrese el nombre" required>
			</div>
			<div class="form-group">
				<label for="text">Imagen descriptiva:</label><br>
				<small><i>*Nota: Procure que la imagen debe tener el nombre rastreable y sin espacios, en su defecto remplazarlos por guion bajo. El tamaño de la imagen debe ser menor a 1.9 MB.</i></small><br>
				<p><input type="file" name="cover" class="form-control" required></p>
			</div>
			<!-- Boton -->
			<div class="form-group"><br>
				<p><input type="submit" value="Enviar Datos" class="btn btn-primary"></p>
			</div><br>
			<!-- Boton -->
		</form>
	</div>
</div>

<div class="col-md-12">
	<div class="white-box">
		<h3>Lista de flores</h3>
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Nombre</th>	
					<th>Imagen</th>
					<th>Acciones</th>
					<th>Editar</th>	
					<th>Eliminar</th>
				</tr> 
			</thead>
			<?php foreach ($this->flores as $flw) { ?>
			<tbody>
				<tr>
					<td><?php echo $flw["nombre"]; ?></a></td>
					<td><img class="img-circle" src="/<?php echo $flw["imagen"];  ?>" width="100" height="100"></td>
					<td><a href="/panel/temporadaflor/id/<?php echo $flw['id']; ?>">Agregar temporadas</a></td>
					<td><a href="/panel/floresedit/id/<?php echo $flw["id"] ?>"><i class="fa fa-2x fa-edit"></i></a></td>
					<td><a href="/panel/requestdeleteflowers/id/<?php echo $flw["id"]; ?>" ><span class="warning" style="color: red;"><i class="fa fa-2x fa-trash"></i></span></a></td>
				</tr>
			</tbody>
			<?php } ?>
		</table>
	</div>
</div>
