<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>	
<div class="col-md-12">
	<div class="white-box">
		<div class="jumbotron" style="background-image: url('/img/card.jpg'); background-size: cover;
        background-position: top center; ">
		    <h1>Editar tarjeta</h1>
		</div>
		<?php $session = new Zend_Session_Namespace("current_session"); 
		                // echo $session->id;
		                echo $session->nombre;
		            ?>
	</div>
</div>

<div class="col-md-12">
	<div class="white-box">
		<form action="/panel/requesttarjetasedit" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
			<?php foreach ($this->tarjeta as $tjt) { ?>
			<div class="form-group">
				<input type="hidden" name="id" value="<?php echo $tjt['id']; ?>">
				<input type="hidden" name="urlhidden" value="<?php echo $tjt['imagen']; ?>">
				<div class="col-md-12 text-left">
					<label for="text">Nombre o tipo de tarjeta:</label>
					<p><input type="text" name="name" class="form-control" value="<?php echo $tjt['nombre']; ?>" placeholder="Ingrese el nombre de la tarjeta" class="form-control"></p>
				</div>
				<div class="col-md-12">
					<label for="text">Imagen descriptiva: </label><br>
					<small><i>*Nota: Procure que la imagen debe tener el nombre rastreable y sin espacios, en su defecto remplazarlos por guion bajo. El tamaño de la imagen debe ser menor a 1.9 MB.</i></small><br>
					<p><input type="file" name="cover" class="form-control" class="form-control"></p>
				</div>
				<div class="col-md-12">
					<select id="view" class="form-control" name="prod">
						<option value="">Seleccione un producto</option>
						<?php foreach ($this->productos as $prod) { ?>
						<option value="<?php echo $prod['id']; ?>"><?php echo $prod['nombre']; ?></option>
						<?php } ?>
					</select>
				</div>
				<?php } ?>
				<!-- Boton -->
				<div class="col-md-12"><br>
					<p><input type="submit" value="Enviar Datos" class="btn btn-primary" class="form-control"></p>
				</div><br>
				<!-- Boton -->
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$("#view").val('<?php echo $tjt["fkpro"] ?>');
	});
</script>