<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<div class="col-md-12">
	<div class="white-box">	
		<div class="jumbotron" style="background-image: url('/img/card.jpg'); background-size: cover;
        background-position: top center; ">
    		<h1>Gestion de tarjeta</h1>
		</div>
		<?php $session = new Zend_Session_Namespace("current_session"); 
                // echo $session->id;
                echo $session->nombre;
            ?>
	</div>
</div>
<div class="col-md-12">
	<div class="white-box">	
		<form action="/panel/requesttarjetasadd" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="form-group">
				<div class="col-md-12">
					<label for="text">Nombre o tipo de tarjeta:</label>
					<p><input type="text" name="name" class="form-control" placeholder="Ingrese el nombre de la tarjeta" required></p>
				</div>
				<div class="col-md-12">
					<label for="text">Imagen descriptiva:</label><br>
					<small><i>*Nota: Procure que la imagen debe tener el nombre rastreable y sin espacios, en su defecto remplazarlos por guion bajo. El tamaño de la imagen debe ser menor a 1.9 MB.</i></small><br>
					<p><input type="file" name="cover" class="form-control" required></p>
				</div>
				<!-- <div class="col-md-12">
						<?php foreach ($this->productos as $prod) { ?>
						<option value="<?php echo $prod['id']; ?>"><?php echo $prod['nombre']; ?></option>
						<?php } ?>
				</div> -->
				<div class="col-md-12">
					<label for="text">Descripción:</label>
						<textarea class="" id="editorDescripcion" rows="100" cols="100"  name="descr"></textarea>
						<script type="text/javascript">CKEDITOR.replace( 'editorDescripcion',{
					height : 100,
				}); </script>
				</div>
				<!-- Boton -->
				<div class="col-md-12 text-center"><br>
					<p><input type="submit" value="Enviar Datos" class="btn btn-primary"></p>
				</div><br>
				<!-- Boton -->
			</div>
		</form>
	</div>
</div>

<div class="col-md-12">
	<div class="white-box">
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Nombre</th>	
					<th>Imagen</th>
					<!-- <th>Producto</th> -->
					<th>Descripcion</th>
					<th>Productos</th>	
					<th>Acciones</th>
				</tr> 
			</thead>
			<?php foreach ($this->tarjetas as $tjt) { ?>
			<tbody>
				<tr>
					<td><?php echo $tjt["nombre"]; ?></a></td>
					<td><img class="img-circle" src="/<?php echo $tjt["imagen"];  ?>" width="100" height="100"></td>
					<!-- <td>
					<?php foreach ($this->productos as $prod) { ?>
					<?php  
					if ($prod['id']==$tjt['fkpro']) { 
						echo $prod['nombre'];					
					} ?>
					<?php } ?>
					</td> -->
					<td><?php echo $tjt["descripcion"]; ?></td>
					<td><a href="/panel/tarjetaproducto/id/<?php echo $tjt['id']; ?>">Agregar</a></td>
					<td>
					<a href="/panel/tarjetaedit/id/<?php echo $tjt["id"] ?>"><i class="fa fa-2x fa-edit"></i></a><br>
					<a href="/panel/requestdeletetarjeta/id/<?php echo $tjt["id"]; ?>" ><span class="warning" style="color: red;"><i class="fa fa-2x fa-trash"></i></span></a></td>
				</tr>
			</tbody>
			<?php } ?>
		</table>
	</div>
</div>