
<div class="col-lg-12">
	<div class="white-box">
		<div class="jumbotron" style="background-image: url('/img/user.png'); background-size: cover;
        background-position: top center; ">
    		<h1>Nuevo Usuario</h1>
		</div>
		<?php $session = new Zend_Session_Namespace("current_session"); 
        		echo $session->nombre;
			?>
	</div>
</div>

<div class="col-md-12">
	<div class="white-box">
		<form action="/panel/requestadduser" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
			<div class="form-group">
				<label for="text">Selecciona un Rol para el Usuario</label>
				<select name="rol" class="form-control">
					<option value="">Selecciona un Rol</option>
					<?php foreach ($this->rol as $option){?>
					<option value="<?php echo $option['id']; ?>">
						<?php echo $option['nombre']; ?>
					</option>
					<?php  }  ?>
				</select> 
				<br>
			</div>
			<div class="form-group">
				<label for="text">Nombre(s): </label>
				<p><input type="text" name="name" class="form-control" placeholder="Ingrese el nombre" required></p>
			</div>
			<div class="form-group">
				<label for="text">Apellido paterno: </label>
				<p><input type="text" name="apa" class="form-control" placeholder="Ingrese el apellido paterno" required></p>
			</div>
			<div class="form-group">
				<label for="text">Apellido materno: </label>
				<p><input type="text" name="ama" class="form-control" placeholder="Ingrese el apellido materno" required></p>
			</div>
			<div class="form-group">
				<label for="text">Dirección: </label>
				<p><input type="text" name="dir" class="form-control" placeholder="Ingrese la direccion" required></p>
			</div>
			<div class="form-group">
				<label for="text">Telefono: </label>
				<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" placeholder="Ingrese el numero telefonico" required></p>
			</div>
			<div class="form-group">
				<label for="text">Correo electronico: </label>
				<p><input type="text" name="mail" class="form-control" placeholder="Ingrese el correo" required></p>
			</div>
			<div class="form-group">
				<label for="text">Contraseña: </label>
				<p><input type="password" name="pword" id="pword" class="form-control" placeholder="Ingrese la contraseña" required></p>
			</div>
			<div class="form-group">
				<label for="text">Confirme contraseña:</label>
				<p><input type="password" name="pwordc" id="pwordc" class="form-control" placeholder="Confirme la contraseña" required></p>
			</div>
			
			<!-- Boton -->
			<div class="form-group text-center"><br>
				<p><input type="submit" value="Enviar Datos" class="btn btn-primary"></p>
			</div><br>
			<!-- Boton -->
		</form>
	</div>
</div>

<!-- ================================================================================================= -->
<div class="col-md-12">

	<div class="white-box">
		<h3>Lista de Usuarios</h3>
			<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Nombre</th>	
					<th>Apellido Paterno</th>
					<th>Apellido Materno</th>	
					<th>Telefono</th>
					<th>Direccion</th>
					<th>Correo</th>
					<th>Rol</th>
				</tr> 
			</thead>
			<?php foreach ($this->usuarios as $usr) { ?>
			<tbody>
				<tr>
					<td><?php echo $usr["nombre"]; ?></td>
					<td><?php echo $usr["ap"]; ?></td>
					<td><?php echo $usr["am"]; ?></td>
					<td><?php echo $usr["telefono"]; ?></td>
					<td><?php echo $usr["direccion"]; ?></td>
					<td><?php echo $usr["correo"]; ?></td>
					<td><?php echo $usr["fkroles"]; ?></td>
					<td>
						<a href="/panel/usuariosedit/id/<?php echo $usr["id"] ?>"><i class="fa fa-2x fa-edit"></i></a>
					</td>
					<td>
						<a href="/panel/requestdeleteall/id/<?php echo $usr["id"]; ?>" ><span class="warning"><i class="fa fa-2x fa-trash" style="color: red"></i></span></a>
					</td>
				</tr>
			</tbody>
			<?php } ?>
		</table>
	</div>
</div>
		

<script type="text/javascript">
	function numeros(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " 0123456789";
		especiales = [8,37,39,46];

		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			} 
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial)
			return false;
	}
</script>

<script>
	var pword, pwordc;

	pword = document.getElementById('pword');
	pwordc = document.getElementById('pwordc');

	pword.onchange = pwordc.onkeyup = passwordMatch;

	function passwordMatch() {
	    if(pword.value !== pwordc.value)
	        pwordc.setCustomValidity('Las contraseñas no coinciden.');
	    else
	        pwordc.setCustomValidity('');
	}  
</script>