<div class="col-md-12">
	<div class="white-box">
		<div class="jumbotron" style="background-image: url('/img/user.png'); background-size: cover;
        background-position: top center; ">
    		<h1 style="color:black ; ">Modificar Usuario</h1>
		</div>
		<?php $session = new Zend_Session_Namespace("current_session"); 
        		echo $session->nombre;
			?>
	</div>
</div>


<div class="col-md-12">
	<div class="white-box">
		<form action="/panel/requestupdateuser" method="POST" enctype="multipart/form-data" class="form-horizontal form-material">
			<?php foreach ($this->usuarios as $usr) { ?>
			<input type="hidden" name="ids" value="<?php echo $usr["id"]; ?>">
			<div class="from-group">
				<label for="text">Nombre(s): </label>
				<p><input type="text" name="name" class="form-control" value="<?php echo $usr["nombre"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Apellido paterno: </label>
				<p><input type="text" name="apa" class="form-control" value="<?php echo $usr["ap"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Apellido materno: </label>
				<p><input type="text" name="ama" class="form-control" value="<?php echo $usr["am"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Dirección: </label>
				<p><input type="text" name="dir" class="form-control" value="<?php echo $usr["direccion"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Telefono: </label>
				<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" value="<?php echo $usr["telefono"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Correo electronico: </label>
				<p><input type="text" name="mail" class="form-control" value="<?php echo $usr["correo"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Contraseña: </label>
				<p><input type="password" name="pword" class="form-control" value="<?php echo $usr["passw"]; ?>"></p>
			</div>
			<div class="from-group">
				<label for="text">Confirme contraseña: </label>
				<p><input type="password" name="pwordc" class="form-control" value="<?php echo $usr["passw"]; ?>"></p>
			</div>
			<?php } ?>
			<!-- Boton -->
			<div class="from-group text-center"><br>
				<p><input type="submit" value="Actializar" class="btn btn-primary" sy></p>
			</div><br>
			<!-- Boton -->
		</div>
	</form>
</div>
</div>


<script type="text/javascript">
	function numeros(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " 0123456789";
		especiales = [8,37,39,46];
		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			} 
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial)
			return false;
	}
</script>