<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
    <title>Temporada de flores</title>
    <!-- Bootstrap Core CSS -->
    <link href="/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
    <!-- Animation CSS -->
    <link href="/css/animate.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/style.css" rel="stylesheet">
    <!-- color CSS you can use different color css from css/colors folder -->
    <!-- We have chosen the skin-blue (blue.css) for this starter
          page. However, you can choose any other skin from folder css / colors .
      -->

      <link href="/css/colors/blue-dark.css" id="theme" rel="stylesheet">
      <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="cssload-speeding-wheel"></div>
    </div>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header"> <a class="navbar-toggle hidden-sm hidden-md hidden-lg " href="javascript:void(0)" data-toggle="collapse" data-target=".navbar-collapse"><i class="fa fa-bars"></i></a>
                <div class="top-left-part" style="padding-left: 10px;">
                    <a class="logo" href="/panel">
<!--                         <b><img src="../plugins/images/pixeladmin-logo.png" alt="home" /></b>
                        <span class="hidden-xs"><img src="/plugins/images/pixeladmin-text.png" alt="home" /></span> -->
                        <h3 class="text-white">Panel Admin</h3>
                    </a>
                </div>
<!--                 <ul class="nav navbar-top-links navbar-left m-l-20 hidden-xs">
                    <li>
                        <form role="search" class="app-search hidden-xs">
                            <input type="text" placeholder="Search..." class="form-control"> <a href=""><i class="fa fa-search"></i></a>
                        </form>
                    </li>
                </ul> -->
                <ul class="nav navbar-top-links navbar-right pull-right">
                    <li>
                        <a class="profile-pic" href="#"> <img src="/plugins/images/users/user.png" alt="user-img" width="36" class="img-circle"><b class="hidden-xs">Admin</b> </a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- Left navbar-header -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse slimscrollsidebar">
                <ul class="nav" id="side-menu">
                    <li style="padding: 10px 0 0;">
                        <a href="/panel/" class="waves-effect"><i class="fa fa-clock-o fa-fw" aria-hidden="true"></i><span class="hide-menu">Dashboard</span></a>
                    </li>
                    <li>
                        <a href="/panel/flores" class="waves-effect"><i class="fa fa-user fa-fw" aria-hidden="true"></i><span class="hide-menu">Flores</span></a>
                        <!-- <a class="nav-link" href="/panel/flores">Flores</a> -->
                    </li>
                    <li>
                        <a href="/panel/productos" class="waves-effect"><i class="fa fa-cubes fa-fw" aria-hidden="true"></i><span class="hide-menu">Productos</span></a>
                    </li>
                    <li>
                        <a href="/panel/recomendaciones" class="waves-effect"><i class="fa fa-check-square fa-fw" aria-hidden="true"></i><span class="hide-menu">Recomendaciones</span></a>
                    </li>
                    <li>
                        <a href="/panel/tarjeta" class="waves-effect"><i class="fa fa-credit-card fa-fw" aria-hidden="true"></i><span class="hide-menu">Tarjeta</span></a>
                    </li> 
                    <li>
                        <a href="/panel/temporada" class="waves-effect"><i class="fa fa-leaf fa-fw" aria-hidden="true"></i><span class="hide-menu">Temporada</span></a>
                    </li> 
                    <li>
                        <a href="/panel/usuarios" class="waves-effect"><i class="fa fa-users fa-fw" aria-hidden="true"></i><span class="hide-menu">Usuarios</span></a>
                    </li> 
                    <li>
                        <a href="/panel/pedidos" class="waves-effect"><i class="fa fa-truck fa-fw" aria-hidden="true"></i><span class="hide-menu">Pedidos</span></a>
                    </li>
                    <li>
                        <a href="/panel/pedidosvendidos" class="waves-effect"><i class="fa fa-usd fa-fw" aria-hidden="true"></i><span class="hide-menu">Pedidos Vendidos</span></a>
                    </li>
                    <!-- <li>
                        <a href="/panel/orden" class="waves-effect"><i class="fa fa-gift fa-fw" aria-hidden="true"></i><span class="hide-menu">Gestión de Orden</span></a>
                    </li>  -->
                    <li>
                        <a href="/index/logout" class="waves-effect"><i class="fa fa-power-off fa-fw" aria-hidden="true"></i><span class="hide-menu">Cerrar Sesión</span></a>
                    </li> 
<!--                     <li>
                        <a href="#" class="waves-effect"><i class="fa fa-info-circle fa-fw" aria-hidden="true"></i><span class="hide-menu"></span></a>
                    </li>    -->                                                                                                                                         
                    <li>
                        <a href="404.html" class="waves-effect"><i class="fa fa-info-circle fa-fw" aria-hidden="true"></i><span class="hide-menu">Error 404</span></a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- Left navbar-header end -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Blank Page </h4> </div>
                        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12"> 
                            <!-- <a href="http://wrappixel.com/templates/pixeladmin/" target="_blank" class="btn btn-danger pull-right m-l-20 btn-rounded btn-outline hidden-xs hidden-sm waves-effect waves-light">Upgrade to Pro</a> -->
                            <ol class="breadcrumb">
                                <li><a href="#">Dashboard</a></li>
                                <li class="active">Blank Page</li>
                            </ol>
                        </div>
                        <!-- /.col-lg-12 -->
                    </div>
                    <div class="row">
<!--                         <div class="col-md-12">
                            <div class="white-box"> -->
                                <!-- <h3 class="box-title">Blank page</h3> -->
                                <?php echo $this->layout()->content; ?>
<!--                             </div>
                        </div> -->
                    </div>
                </div>
                <!-- /.container-fluid -->
                <footer class="footer text-center"> 2018 &copy; Developed by Ich-Element </footer>
            </div>
            <!-- /#page-wrapper -->
        </div>
        <!-- /#wrapper -->
        <!-- jQuery -->
        <script src="/plugins/bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- Menu Plugin JavaScript -->
        <script src="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>
        <!--slimscroll JavaScript -->
        <script src="/js/jquery.slimscroll.js"></script>
        <!--Wave Effects -->
        <script src="/js/waves.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="/js/custom.min.js"></script>
    </body>
    </html>