<div class="col-md-12">
    <h2>Mis Compras Finalizadas</h2>
    <table class="table table-bordered table-striped">                    
        <thead>
            <tr>
                <th>Orden</th>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>Direccion</th>
                
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->complete as $k){ 
                if($k['iscomplete']==1){?>
                    <tr>
                        <td><p><?php echo $k["id"];?></p></td>
                        <td><p><?php echo $k["nombre"]; ?></p></td>
                        <td><p><?php echo $k["idusuario"]; ?></p></td>
                        <td><p><?php echo $k["iddireccion"];?></p></td>
                        
                        <td>
                            <a href="/panel/detallepedidos/id/<?php echo $key["id"]; ?>"><i class="fa fa-info" style="color: blue;">Detalles</i></a>
                        </td>                        
                    </tr>    
            <?php } } ?>
        </tbody>  
    </table>
</div>