<h1>Direcciones guardadas</h1>
<div class="row">
	<div class="col-lg-12">
		<div class="col-lg-12 text-right">
			<?php foreach ($this->usuario as $usr) { ?>
				<a href="/home/nuevadireccion/id/<?php echo $usr['id']; ?>">Agregar direccion</a>
			<?php } ?>
		</div>
		<table class="table text-left table-hover">
			<thead>
				<tr>
					<th>Direccion</th>
					<th>Eliminar</th>
				</tr> 
			</thead>
			<?php foreach ($this->direcciones as $key) { ?>
			<tbody>
				<tr>
					<td><?php echo $key["direccion"]; ?></td>
					<td><a href="/home/requestdeletedireccion/id/<?php echo $key["id"]; ?>" ><span class="warning" style="color: red;"><i class="fa fa-2x fa-trash"></i></span></a></td>
				</tr>
			</tbody>
			<?php } ?>
		</table>	
	</div>	
</div>