<div class="jumbotron" style="background-color: #ffffff;">
    <h1>Nuevo Usuario</h1>
</div>

<div class="row">
	<div class="col-lg-12">
		<form action="/home/requestupdateusersession" method="POST" enctype="multipart/form-data">
			<?php foreach ($this->usuario as $usr) { ?>
			<div>
				<input type="hidden" name="rol" value="2">
				<br>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Nombre(s): </h4></label>
					<p><input type="text" name="name" class="form-control" placeholder="Ingrese el nombre" value="<?php echo $usr['nombre']; ?>" required></p>
				</div>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Apellido paterno: </h4></label>
					<p><input type="text" name="apa" class="form-control" placeholder="Ingrese el Apellido Paterno" value="<?php echo $usr['ap']; ?>" required></p>
				</div>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Apellido materno: </h4></label>
					<p><input type="text" name="ama" class="form-control" placeholder="Ingrese el Apellido Materno" value="<?php echo $usr['am']; ?>" required></p>
				</div>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Dirección: </h4></label>
					<p><input type="text" name="dir" class="form-control" placeholder="Ingrese la Direccion" value="<?php echo $usr['direccion']; ?>" required></p>
				</div>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Telefono: </h4></label>
					<p><input type="text" name="phone" class="form-control" onkeypress="return numeros(event)" value="<?php echo $usr['telefono']; ?>" maxlength="10" required></p>
				</div>
				<div class="col-lg-12 text-left">
					<label for="text"><h4>Correo electronico: </h4></label>
					<p><input type="mail" name="mail" id="mail" class="form-control" placeholder="Example@mail.com" value="<?php echo $usr['correo']; ?>" required></p>
				</div>
			</div>
			<?php } ?>
			<!-- Boton -->
			<div class="col-lg-12 text-center"><br>
				<p><input type="submit" value="Guardar" class="btn btn-primary"></p>
			</div><br>
			<!-- Boton -->
		</form>
	</div>
</div>

<script type="text/javascript">
	function numeros(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " 0123456789";
		especiales = [8,37,39,46];

		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			} 
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial)
			return false;
	}
</script>