<h1>Mis Pedidos activos</h1>

<div class="col-md-12">
    <table class="table table-bordered table-striped">                    
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Usuario</th>
                <th>direccion</th>
            </tr>
        </thead>
        <tbody>
            <?php $cont =1;
                foreach ($this->orden as $key){ 
                     if($key['iscomplete']==0){ ?>
                    <tr>
                        <th scope="row"><?php echo $cont++; ?></th>
                        <td><p><?php echo $key["nombre"]; ?></p></td>
                        <td><p><?php echo $key["idusuario"]; ?></p></td>
                        <td><p><?php echo $key["iddireccion"];?></p></td>
                        <td>
                        	<a href="/home/detallespedidos/id/<?php echo $key["id"]; ?>"><i class="fa fa-info" style="color: blue;">Detalles</i></a>
                        </td>
                    </tr>    
            <?php } } ?>
        </tbody>  
    </table>
</div> 