<div class="col-md-12">
  <div class="white-box">
  	
	    <div class="col-md-12 text-center">
	      <h2>Recuperacion de Contraseña</h2> <br>       
	    </div>
    
	    <div class="col-md-12">
	      <h4 class="text-center inner-padding">Ingrese correo </h4>
	      <form method="POST" action="/tokens/validar" class="form-horizontal form-material">
	        <div class="form-group">
	            <div class="col-md-12">
	              <label><i class="fa fa-user" aria-hidden="true"></i> Correo</label>
	              <input type="text" name="correo"  class="form-control" placeholder="Ingrese el correo"/>    
	            </div>
	            <br>
	            <div class="col-md-12 text-center">
	             <input type="submit" value="Enviar" class="btn btn-primary"/>
	           </div>
	       </div>     
	     </form>
	   </div> 
	</div>           
 </div>
</div>